name: 'Build Mindbridge'

on:  
  pull_request:
    branches:
      - main
      - dev

jobs:
  terraform:
    name: 'Project Build'
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1   
        
      - name: Build Backend docker image
        id: docker-build-backend        
        uses: docker/build-push-action@v2
        with:
          context: .
          file: .docker/backend.Dockerfile
          push: false
          tags: ${{ secrets.BACKEND_DOCKER_REGISTRY }}:latest

      - name: Build Frontend docker image
        id: docker-build-frontend        
        uses: docker/build-push-action@v2
        with:
          context: .
          file: .docker/frontend.Dockerfile
          push: false
          tags: ${{ secrets.FRONTEND_DOCKER_REGISTRY }}:latest